### ISSUE TITLE
Todo list for EthShanghai2023

### ISSUE THREAD

**Issue by CryptoCatty** [Soul-Avatars/soul-avatars-dapp#1]
- [x] add multi-bot support.
- [x] deploy to vercel.
- [x] add connect wallet button.
- [x] get bots data from NFTs.
- [x] define bot characteristics from NFT props.
- [x] bug fix: don't show auth link when chat request failed.
- [x] sys prompt update.
- [x] show NFT name for new contract.
- [x] avart image style update for new image.
- [ ] add NFT market place.

more:
- [x] slides and video.

**Comment by CryptoCatty** [comment]
hackathon finished
